### ISSUE TITLE
Move sensitive identifiers from Github Actions workflow into secrets.

### ISSUE THREAD

**Issue by felddy** [cisagov/domain-manager-cicd#10]
AWS account IDs are considered [sensitive information](https://github.com/cisagov/development-guide/blob/develop/open-source-policy/practice.md#protecting-sensitive-information).  

https://github.com/cisagov/domain-manager-cicd/blob/aa48571a8a62570e019294663241f174d2a160f7/.github/workflows/cool.yml#L11-L12

Please remove these from the repository and store them as [encrypted secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#about-encrypted-secrets).

**Comment by mcdonnnj** [comment]
@felddy Should cleaning the git history be part of the requirements?

**Comment by zenine07** [comment]
@felddy @mcdonnnj Sorry, didn't realize account ids are considered sensitive information. I'm assuming all of this information would be considered sensitive as well then. 

https://github.com/cisagov/domain-manager-cicd/blob/fd1ccd25405cdb1f9b6b040d28a44f8a08ad9fcc/cool/vars/staging.tfvars#L4-L7

Do you have already have a process for managing tfvars in an S3 bucket or something? Or do I have to add everything in as Github secrets?

**Comment by felddy** [comment]
> @felddy @mcdonnnj Sorry, didn't realize account ids are considered sensitive information. I'm assuming all of this information would be considered sensitive as well then.
> 
> https://github.com/cisagov/domain-manager-cicd/blob/fd1ccd25405cdb1f9b6b040d28a44f8a08ad9fcc/cool/vars/staging.tfvars#L4-L7
> 
> Do you have already have a process for managing tfvars in an S3 bucket or something? Or do I have to add everything in as Github secrets?

Yes.  Those should also be evicted.  

We have settled on using "profiles" as our method of distributing roles:

https://github.com/cisagov/freeipa-client-packer/blob/8a4c52db6f425e3c8c9f9164426dfe193bf45b95/terraform-test-user/main.tf#L2-L19

The profiles are stored locally in your [AWS credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider)

We created a tool that we use to synchronize credentials amongst our team since we have myriad profiles now in multiple workspaces: 
https://github.com/cisagov/aws-profile-sync

It would probably be overkill to use it for a single profile or two that don't change often.

**Comment by felddy** [comment]
> @felddy Should cleaning the git history be part of the requirements?

I don't think there is a need to edit the history for this.  I believe a cleanup is reasonable for this event.

**Comment by zenine07** [comment]
> Yes. Those should also be evicted.
> 
> We have settled on using "profiles" as our method of distributing roles:
> 
> https://github.com/cisagov/freeipa-client-packer/blob/8a4c52db6f425e3c8c9f9164426dfe193bf45b95/terraform-test-user/main.tf#L2-L19
> 
> The profiles are stored locally in your [AWS credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider)
> 
> We created a tool that we use to synchronize credentials amongst our team since we have myriad profiles now in multiple workspaces:
> https://github.com/cisagov/aws-profile-sync
> 
> It would probably be overkill to use it for a single profile or two that don't change often.

@felddy Awesome. The reason I wasn't using a profile is it's a bit difficult to inject a profile into Github Actions, as we use it to run our deployments and terraform, but I'll figure out a simple way and get it out of the tfvars file.
